# Generated by Django 4.1.4 on 2023-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
