# Generated by Django 4.1.4 on 2022-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacherevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
