# Generated by Django 4.1.4 on 2023-01-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_freelancing_project_skill_student_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_num',
            field=models.CharField(default='Test', max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_description',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='talks_about',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
