# Generated by Django 4.1.4 on 2023-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_teacher_phone_num_teacher_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='total_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
