# Generated by Django 4.1.4 on 2023-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_course_passing_marks_course_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_num',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='talks_about',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
