# Generated by Django 4.1.4 on 2023-01-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_student_phone_num_student_profile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.TextField()),
                ('giver_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_giver', to='management.student')),
                ('reciever_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_reciever', to='management.student')),
            ],
        ),
    ]
