# Generated by Django 4.1.4 on 2023-01-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_endorsement_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('cgpa', models.FloatField()),
                ('requirements', models.TextField()),
                ('job_description', models.TextField()),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.recruiter')),
            ],
        ),
    ]
