# Generated by Django 4.1.4 on 2023-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portfolio',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
