# Generated by Django 4.1.4 on 2023-01-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_student_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(default='Full Time', max_length=200),
            preserve_default=False,
        ),
    ]
