# Generated by Django 4.1.4 on 2023-01-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_experience_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_name',
            field=models.TextField(default='Raspberry Pi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancing',
            name='level',
            field=models.CharField(default='Beginner', max_length=200),
            preserve_default=False,
        ),
    ]
