# Generated by Django 4.1.4 on 2023-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='top_skill',
            new_name='top_skill1',
        ),
        migrations.AddField(
            model_name='project',
            name='top_skill2',
            field=models.CharField(default='Test Skill', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='top_skill3',
            field=models.CharField(default='Test Skill 3', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='github',
            field=models.CharField(default='Test Github', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='looking_for',
            field=models.CharField(default='Hard Working Student', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='working_since',
            field=models.CharField(default=2009, max_length=100),
            preserve_default=False,
        ),
    ]
