# Generated by Django 4.1.4 on 2023-02-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_rename_top_skill_project_top_skill1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
