# Generated by Django 4.1.4 on 2023-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_debate_sports_student_debate_student_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='document',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='document/'),
        ),
    ]
